# Generated by Django 4.2.18 on 2025-05-07 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_entree_ligneentree_lignesortie_sortie_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='couleur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.couleur'),
        ),
        migrations.AlterField(
            model_name='article',
            name='forme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.forme'),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.type'),
        ),
    ]
