# Generated by Django 4.2.18 on 2025-05-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_article_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortie',
            name='date_sor',
            field=models.DateField(default='2025-05-07'),
            preserve_default=False,
        ),
    ]
